theme = "slick"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
interval = 5

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

